protected/models/Project.php
<?php

/**
 * This is the model class for table "project".
 *
 * The followings are the available columns in table 'project':
 */
class Project extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Project the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{project}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('projectName, svnProjectName, svnProjectPath', 'required'),
			array('projectName, svnProjectName, svnProjectPath', 'length', 'max'=>255),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
		    array('svnUser, svnPass, noPubList, isRemove', 'safe'),
			array('projectId, projectName, svnProjectName, svnProjectPath, isRemove', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		    'users'=>array(self::MANY_MANY, 'User', '{{project_user}}(projectId, userId)'),
		    'hosts'=>array(self::MANY_MANY, 'Host', '{{project_host}}(projectId, hostId)'),
		);
	}

	public function scopes() {
		return array(
		    'dropDownDataByUser'=>array(
				'select'=>'projectId,projectName',
				'with'=>'users',
		    )
		);
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'projectId' => 'Project',
			'projectName' => '项目名称',
			'svnProjectName' => 'Svn项目名',
			'svnProjectPath' => 'Svn项目地址',
			'svnUser'=>'Svn帐号',
			'svnPass'=>'Svn密码',
			'isRemove'=>'删除Svn文件',
			'noPubList'=>'不发布列表'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('projectId',$this->projectId);
		$criteria->compare('projectName',$this->projectName,true);
		$criteria->compare('svnProjectName',$this->svnProjectName,true);
		$criteria->compare('svnProjectPath',$this->svnProjectPath,true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/models/ProjectForm.php
<?php

/**
 * LoginForm class.
 * LoginForm is the data structure for keeping
 * user login form data. It is used by the 'login' action of 'SiteController'.
 */
class ProjectForm extends CFormModel
{
	public $project_id;
	public $project_name;
	public $svn_project_name;
	public $svn_project_path;
	public $svn_user;
	public $svn_pass;
	public $nopub_list;
	public $is_remove;
	public $test_host;
	public $prod_host;
	 
	/**
	 * Declares the validation rules.
	 * The rules state that username and password are required,
	 * and password needs to be authenticated.
	 */
	public function rules()
	{
		return array(
		    array('project_name, svn_project_name, svn_project_path', 'required'),
		    array('test_host', 'required', 'message'=>'{attribute} 至少选择一个'),
		    array('project_name, svn_project_name, svn_project_path', 'length', 'max'=>255),
		    array('project_id, project_name, svn_project_name, svn_project_path, svn_user, svn_pass, nopub_list, is_remove, test_host, prod_host', 'safe'),
		);
	}

	/**
	 * Declares attribute labels.
	 */
	public function attributeLabels()
	{
		return array(
			'project_id' => 'Project',
			'project_name' => '项目名称',
			'test_host' => '测试主机',
			'prod_host' => '生产主机',
			'distribute_host_list' => '分发地址及路径列表',
			'svn_project_name' => 'Svn项目名',
			'svn_project_path' => 'Svn项目地址',
		        'nopub_list'=>'不发文件布列表',
		        'is_remove'=>'删除svn中已删除的文件'
		);
	}

	/**
	 * Authenticates the password.
	 * This is the 'authenticate' validator as declared in rules().
	 */
	public function authenticate($attribute,$params)
	{
		if(!$this->hasErrors())
		{
			$this->_identity=new UserIdentity($this->username,$this->password);
			if(!$this->_identity->authenticate())
				$this->addError('password','用户名或密码不正确。');
		}
	}

	/**
	 * Logs in the user using the given username and password in the model.
	 * @return boolean whether login is successful
	 */
	public function login()
	{
		if($this->_identity===null)
		{
			$this->_identity=new UserIdentity($this->username,$this->password);
			$this->_identity->authenticate();
		}
		if($this->_identity->errorCode===UserIdentity::ERROR_NONE)
		{
			$duration=$this->rememberMe ? 3600*24*30 : 0; // 30 days
			Yii::app()->user->login($this->_identity,$duration);
			return true;
		}
		else
			return false;
	}
}

protected/controllers/HostController.php
<?php

class HostController extends Controller
{

	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}
	
	
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to perform 'index' and 'view' actions
						'roles'=>array('admin'),
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*')
				)
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Host;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$distributeHostList = Yii::app()->request->getPost('distributeHostList', '');
		if(isset($_POST['Host']))
		{
			$model->attributes=$_POST['Host'];
			if($model->save()) {
				$model->insertDistributeHost($distributeHostList);
				$this->redirect(array('view','id'=>$model->hostId));
			}
			
		}

		$this->render('create',array(
			'model'=>$model,
			'distributeHostList'=>$distributeHostList
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		$distributeHostList = '';
		$lists = Yii::app()->db->createCommand()
						->from('{{distribute_host}}')
						->select('host, port, pubPath, archivePath, tmpPath, scriptLogPath')
						->where('hostId=?')
						->queryAll(false, array($model->hostId));
		if (count($lists)>0) {
			foreach($lists as $key => $value) {
				$lists[$key] = join(':', $value);
			}
			$distributeHostList = join("\n", $lists);
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Host']))
		{
			$model->attributes=$_POST['Host'];
			if($model->save())
				$distributeHostList = Yii::app()->request->getPost('distributeHostList', '');
				$model->deleteDistributeHost();
				$model->insertDistributeHost($distributeHostList);
				$this->redirect(array('view','id'=>$model->hostId));
		}

		$this->render('update',array(
			'model'=>$model,
			'distributeHostList'=>$distributeHostList
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			$sql = "DELETE FROM {{project_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));

			$sql = "DELETE FROM {{user_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			$sql = "DELETE FROM {{distribute_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Host('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Host']))
			$model->attributes=$_GET['Host'];

		$this->render('index',array(
			'model'=>$model,
		));
	}



	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Host::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='host-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	

}

protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{

	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}
	
	
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to perform 'index' and 'view' actions
						'roles'=>array('admin'),
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*')
				)
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$hostListData = CHtml::listData(Host::model()->findAll(),'hostId','hostText', 'hostType');
		$prodHostListData = isset($hostListData[1]) ? $hostListData[1] : array(); //生产主机
		$testHostListData = isset($hostListData[0]) ? $hostListData[0] : array(); //测试主机
		
		$testHostIds = array();
		$prodHostIds = array();
		
		$model=new Project;

		if(isset($_POST['Project']))
		{
			$model->attributes=$_POST['Project'];
			if ($model->save()) {
				//主机列表
				$prodHostIds = isset($_POST['prodHostIds']) ? $_POST['prodHostIds'] : array();
				$testHostIds = isset($_POST['testHostIds']) ? $_POST['testHostIds'] : array();
				$hostIds = array_merge($prodHostIds, $testHostIds);
				if (is_array($hostIds) && count($hostIds)>0) {
					$sql = "INSERT INTO {{project_host}} (hostId, projectId) VALUES ";
					foreach($hostIds as $hostId) {
						$sql .= " ($hostId, $model->projectId),";
					}
					$sql = trim($sql, ",");
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				$this->redirect(array('view','id'=>$model->projectId));
			}
		}


		$this->render('create',array(
			'model'=>$model,
			'testHostIds'=>$testHostIds,
			'prodHostIds'=>$prodHostIds,
		    'prodHostListData'=>$prodHostListData,
			'testHostListData'=>$testHostListData
		    
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		$hostListData = CHtml::listData(Host::model()->findAll(),'hostId','hostText', 'hostType');
		$prodHostListData = isset($hostListData[1]) ? $hostListData[1] : array(); //生产主机
		$testHostListData = isset($hostListData[0]) ? $hostListData[0] : array(); //测试主机
		
		$testHostIds = array();
		$prodHostIds = array();
		
		//测试主机ID列表
		$testHostIds = Yii::app()->db->createCommand()
							->from('{{project_host}} t')
							->select('t.hostId')
							->join('{{host}} h', 't.hostId=h.hostId AND hostType=0')
							->where('projectId=?')
							->queryColumn(array($id));
		if (is_null($testHostIds)) $testHostIds = array();
		
		//产生主机ID列表
		$prodHostIds = Yii::app()->db->createCommand()
							->from('{{project_host}} t')
							->select('t.hostId')
							->join('{{host}} h', 't.hostId=h.hostId AND hostType=1')
							->where('projectId=?')
							->queryColumn(array($id));
		if (is_null($prodHostIds)) $prodHostIds = array();

		
		if(isset($_POST['Project']))
		{
			$model->attributes = $_POST['Project'];
			if ($model->save(false)) {
				$sql = "DELETE FROM {{project_host}} WHERE projectId=?";
				Yii::app()->db->createCommand($sql)->execute(array($model->projectId));
				
				//主机列表
				$prodHostIds = isset($_POST['prodHostIds']) ? $_POST['prodHostIds'] : array();
				$testHostIds = isset($_POST['testHostIds']) ? $_POST['testHostIds'] : array();
				$hostIds = array_merge($prodHostIds, $testHostIds);
				if (is_array($hostIds) && count($hostIds)>0) {
					$sql = "INSERT INTO {{project_host}} (hostId, projectId) VALUES ";
					foreach($hostIds as $hostId) {
						$sql .= " ($hostId, $model->projectId),";
					}
					$sql = trim($sql, ",");
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				$this->redirect(array('view','id'=>$model->projectId));
			}
		}

		$this->render('update',array(
			'model'=>$model,
			'testHostIds'=>$testHostIds,
			'prodHostIds'=>$prodHostIds,
		    'prodHostListData'=>$prodHostListData,
			'testHostListData'=>$testHostListData
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			$sql = "DELETE FROM {{project_host}} WHERE projectId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));

			$sql = "DELETE FROM {{project_user}} WHERE userId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Project('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Project']))
			$model->attributes=$_GET['Project'];

		$this->render('index',array(
			'model'=>$model,
		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Project::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='project-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/project/_form.php
    <div class="wide form">
        <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'user-form',
                'enableAjaxValidation'=>false,
        )); ?>
      <div class="view-toolbar">
          <?php echo CHtml::link('取消', array('/project/index'));?>&nbsp;|&nbsp;
          <?php echo CHtml::submitButton($model->isNewRecord ? '添加' : '保存'); ?>
        </div>
        <table>
          <colgroup>
          <col style="width:20%">
          <col style="width:30%">
          <col style="width:20%">
          <col style="width:30%">
          </colgroup>
          <tbody>
            <tr>
              <th><?php echo $form->labelEx($model,'projectName'); ?></th>
              <td colspan="1">
              <?php echo $form->textField($model,'projectName',array('size'=>60,'maxlength'=>50)); ?>
              <br />项目名称，用于区分不同的项目
              <?php echo $form->error($model,'projectName'); ?>
              </td>
              <th><?php echo $form->labelEx($model,'svnProjectPath'); ?></th>
              <td colspan="1">
              <?php echo $form->textField($model,'svnProjectPath',array('size'=>60,'maxlength'=>50)); ?>
              <br />SVN项目路径，最终checkout的路径，如svn://localhost/help或svn://localhost/help/trunk等
              <?php echo $form->error($model,'svnProjectPath'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo $form->labelEx($model,'svnProjectName'); ?></th>
              <td colspan="1">
				<?php echo $form->textField($model,'svnProjectName',array('size'=>60,'maxlength'=>100)); ?>
				<br />SVN项目名称，用于区分同仓库下的不同路径，如果svn://localhost/help/trunk
				<br />help为项目名，trunk为目录名,则此处填写trunk,如果svn://localhost/help/branches/br-help
				<br />则此处填写branches/br-help
				<?php echo $form->error($model,'svnProjectName'); ?>
              </td>
              <th><?php echo $form->label($model,'isRemove'); ?></th>
              <td colspan="1">
              	<?php echo $form->checkBox($model,'isRemove', array('value'=>1, 'checked'=>$model->isRemove==1?true:false)); ?>
				<br />是否从发布服务器中，删除svn中已删除的文件
			</td>
            </tr>
            <tr>
              <th><?php echo $form->labelEx($model,'svnUser'); ?></th>
              <td colspan="1">
				<?php echo $form->textField($model,'svnUser',array('size'=>60,'maxlength'=>100)); ?>
				<br />项目的svn帐号
				<?php echo $form->error($model,'svnUser'); ?>
              </td>
              <th><?php echo $form->label($model,'svnPass'); ?></th>
              <td colspan="1">
              	<?php echo $form->textField($model,'svnPass',array('size'=>60,'maxlength'=>100)); ?>
				<br />项目的svn密码
				<?php echo $form->error($model,'svnPass'); ?>
			</td>
            </tr>
            <tr>
              <th><?php echo $form->labelEx($model,'noPubList'); ?></th>
              <td colspan="1">
				<?php echo $form->textArea($model,'noPubList',array('rows'=>6, 'cols'=>50, 'style'=>'width:515px;height:150px;')); ?>
				<br />不需要发布到发布服务器的文件/目录列表，回车分开
              </td>
              <th>-</th>
              <td colspan="1">
              	-
			</td>
            </tr>
            
            <tr>
              <th><?php echo CHtml::label('测试服务器','testHostIds[]');?></th>
              <td colspan="1">
				<?php echo CHtml::dropDownList('testHostIds[]',
						$testHostIds,
						$testHostListData,
						array(
							'multiple'=>true,
						        'style'=>'width:520px;height:100px;'	
						)
					);?>
              </td>
              <th><?php echo CHtml::label('生成服务器','prodHostIds[]');?></th>
              <td colspan="1">
              		<?php echo CHtml::dropDownList('prodHostIds[]',
						$prodHostIds,
						$prodHostListData,
						array(
							'multiple'=>true,
						        'style'=>'width:520px;height:100px;'	
						)
					);?>
			 </td>
            </tr>
          </tbody>
        </table>
    </div>
    <?php $this->endWidget(); ?>
  </div>

protected/views/project/create.php
<?php
$this->pageTitle=Yii::app()->name . ' - 添加项目';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>添加项目</h1>
			</div>
		</div>
		<div class="MetadataView">

		<?php echo $this->renderPartial('_form', 
			array(
				'model'=>$model,
				'testHostIds'=>$testHostIds,
				'prodHostIds'=>$prodHostIds,
			    'prodHostListData'=>$prodHostListData,
				'testHostListData'=>$testHostListData
			)); ?>
		
		</div>
	</div>

</div>

protected/views/project/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - 项目列表';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>项目列表</h1>
			</div>
		</div>
		<div class="MetadataView">
		
		<?php $this->widget('zii.widgets.grid.CGridView', array(
			'id'=>'project-grid',
			'htmlOptions'=>array(
					'class'=>'cgrid-view'
			),
			'dataProvider'=>$model->search(),
			'filter'=>$model,
			'columns'=>array(
				array('header'=>'项目名称', 'name'=>'projectName'),
				array('header'=>'SVN项目名', 'name'=>'svnProjectName'),
				array('header'=>'SVN路径', 'name'=>'svnProjectPath'),
				array(
					'header'=>'操作',
					'class'=>'CButtonColumn',
				),
			),
		)); ?>
		
		</div>
	</div>
</div>

protected/views/project/update.php
<?php
$this->pageTitle=Yii::app()->name . ' - 修改项目';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>修改项目 <?php echo $model->projectName; ?></h1>
			</div>
		</div>
		<div class="MetadataView">

<?php echo $this->renderPartial('_form', 
	array(
			'model'=>$model,
			'testHostIds'=>$testHostIds,
			'prodHostIds'=>$prodHostIds,
		    'prodHostListData'=>$prodHostListData,
			'testHostListData'=>$testHostListData
	    )); ?>

		
		</div>
	</div>

</div>

protected/views/project/view.php
<?php
$this->pageTitle=Yii::app()->name . ' - 查看项目';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>查看项目 <?php echo $model->projectName; ?></h1>
			</div>
		</div>
		<div class="MetadataView">
      <div class="view-toolbar">
          <?php echo CHtml::link('返回', array('/project/index'));?>
        </div>
        <table>
          <colgroup>
          <col style="width:20%">
          <col style="width:30%">
          <col style="width:20%">
          <col style="width:30%">
          </colgroup>
          <tbody>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'projectName'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'projectName'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'svnProjectPath'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'svnProjectPath'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'svnProjectName'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'svnProjectName'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'isRemove'); ?></th>
              <td colspan="1">
              <?php echo $model->isRemove==1?'是':'否'; ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'svnUser'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'svnUser'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'svnPass'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'svnPass'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'noPubList'); ?></th>
              <td colspan="1">
              <?php
              	echo nl2br(CHTML::value($model, 'noPubList', '&nbsp;'));
              ?>
              </td>
              <th>-</th>
               <td colspan="1">-</td>
            </tr>
            <?php 
            //可用测试服务器
            $testHosts = array();
            //可用生成服务器
            $prodHosts = array();
            if (isset($model->hosts) && is_array($model->hosts)) {
            	foreach($model->hosts as $host) {
            		if ($host->hostType==1) {
            			$prodHosts[$host->hostId] = $host->hostText;
            		}
            		else {
            			$testHosts[$host->hostId] = $host->hostText;
            		}
            	}
            
            }
            ?>
            <tr>
              <th><?php echo CHtml::label('测试服务器','testHostIds');?></th>
              <td colspan="3">
              <?php 
              	if (is_array($testHosts)) :
              		$no = 1;
              		foreach ($testHosts as $key => $value) :
              			echo CHtml::link($no.':'.$value, array('host/view', 'id'=>$key));
              			echo '&nbsp;';
              			$no++;
              		endforeach;
              	endif;
              ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::label('生成服务器','prodHostIds');?></th>
              <td colspan="3">
              <?php 
              	if (is_array($prodHosts)) :
              		$no = 1;
              		foreach ($prodHosts as $key => $value) :
              			echo CHtml::link($no.':'.$value, array('host/view', 'id'=>$key));
              			echo '&nbsp;';
              			$no++;
              		endforeach;
              	endif;
              ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::label('svn提交钩子','svnhook');?></th>
              <td colspan="3">
              <?php 
              $post_commit_path = Yii::getPathOfAlias('application.data').'/post-commit';
              $template = file_get_contents($post_commit_path);
              $template = strtr($template, array('{{projectId}}'=>$model->projectId, '{{svnProjectName}}'=> $model->svnProjectName));
              
              echo CHtml::textArea('svnhook', $template, array('rows'=>50, 'cols'=>100));
              ?>
              </td>
            </tr>
          </tbody>
        </table>
		
		</div>
	</div>

</div>