protected/models/PubLog.php
<?php

class PubLog extends CActiveRecord
{

	public $createTime_range = array();
	/**
	 * Returns the static model of the specified AR class.
	 * @return Log the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{pub_log}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('logId, pubUser, projectId, archive, hostId, fileList, host, reason', 'required'),
			array('logId, projectId, hostId', 'numerical', 'integerOnly'=>true),
			array('archive', 'length', 'max'=>255),
		    array('fileList, hostId', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('logId, pubUser, projectId, archive, createTime, createTime_range, hostId', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		    'project'=>array(self::BELONGS_TO, 'Project', 'projectId'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'logId' => 'Log',
			'pubUser' => '发布者',
			'projectId' => '项目Id',
			'archive' => '档案名',
			'createTime' => '发布时间',
			'host' => '发布主机',
		    'fileList'=>'文件列表',
		    'reason'=>'发布原因',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search($projectId=0)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.
		
		$criteria=new CDbCriteria;
		if ($projectId!=0) {
			$criteria->addCondition('projectId=:projectId');
			$criteria->params=array('projectId'=>$projectId);
		}
		
		$criteria->compare('pubUser',$this->pubUser,true);
		$criteria->compare('archive',$this->archive,true);

		//createTime
		$to = '';
		if (isset($this->createTime_range['to'])) {
			$to= $this->createTime_range['to'];
		}

		if ($to!='') {
			$createTime = date("Y-m-d", strtotime($to));
			$criteria->compare('createTime',$createTime,true);
		}

		if (!isset($_GET[get_class($this).'_sort']))
			$criteria->order='t.createTime DESC';
		
		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/LogController.php
<?php

class LogController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('admin', 'view'),
				'users'=>array('@'),
			),
		    
			
		        array('allow',
			   
				'actions'=>array('admin', 'create','update', 'delete', ),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Log;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Log']))
		{
			$model->attributes=$_POST['Log'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->log_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Log']))
		{
			$model->attributes=$_POST['Log'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->log_id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{

		
		$dataProvider=new CActiveDataProvider('Log');
		/*, array(
		    'condition'=>'project_id=:project_id',
		    'params'=>array('project_id'=>$defaultProjectId)
		));*/
		
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		
		//用户可用项目列表
		$modelProjects= Project::model()->findAll(array(
		    'with'=>array('users'),
		    'condition'=>'users.userId = ?',
		    'params'=>array(Yii::app()->user->id)
		));	//用户可用项目

		if (count($modelProjects)<=0) {
			echo "<script>alert('你暂时没有被分配项目');location.href='". $this->createUrl('site/index'). "';</script>";
			exit;
		}
		
		$projectListData = array();
		$projectsSvnName = array();
		$defaultProjectId = '';
		

		foreach($modelProjects as $project) {
			if ($defaultProjectId=='') $defaultProjectId = $project->project_id;
			$projectListData[$project->project_id]=$project->project_name;
			$projectsSvnName[$project->project_id]=$project->svn_project_name;
		}

		
		if (isset($_GET['project_id'])) {
			$project_id = (int) $_GET['project_id'];
			foreach($projectListData as $id=>$value) {
				if ($id==$project_id) {
					$defaultProjectId = $project_id;
					break;
				}
			}
		}
		

		//获得项目可用测试上传主机
		$modelHosts = Host::model()->findAll(array(
			'condition'=>'host_type=1',
		    	'with'=>array(
					'projects'=>array(    
						'condition'=>'projects.project_id='. $defaultProjectId,
					),	
					'users'=>array(
					    'condition'=>'users.userId='. Yii::app()->user->getId()
					)
				),
		));
		
		$hostListData = array();
		if (!is_null($modelHosts) && is_array($modelHosts)) {
			foreach($modelHosts as $modelHost) {
				$hostListData[$modelHost->host_id] = $modelHost->host_text." (".$modelHost->host.":".$modelHost->pub_path.")"; 
			}
		}
		
		$model=new Log('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Log']))
			$model->attributes=$_GET['Log'];

		$this->render('admin',array(
			'model'=>$model,
		        'defaultProjectId'=>$defaultProjectId,
		        'hostListData'=>$hostListData,
		        'projectListData'=>$projectListData
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Log::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='log-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PublogController.php
<?php

class PublogController extends Controller
{

	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to perform 'index' and 'view' actions
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*')
				)
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}


	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			$row = Yii::app()->db->createCommand()->from('{{pub_log}} l')
				->where('l.logId='.$id)
				->join('{{host}} h', 'h.hostId=l.hostId')
				->queryAll();
			
			$ssh = new ESsh($row['host'], $row['port'], $row['username'], $row['password']);
			if ($ssh==null) return '无法连接发布主机';
			
			$archiveFile = $row['archivePath'].'/'.$row['archive'];
			$ssh->exec("/bin/rm -rf  $archiveFile");	//删除服务器上的
			@unlink(Yii::app()->params['archivesPath'].'/'.$row['archive']);	//删除本地的
			@unlink(Yii::app()->params['scriptPath'].'/'.$row['script']);	//删除本地脚本
			
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	public function actionRemove()
	{
		$uploadIds = $_POST['uploadIds'];
		$projectId = $_POST['projectId'];
		
		$rows = Yii::app()->db->createCommand()->from('{{pub_log}} l')
				->where('l.logId in ('. $uploadIds .')')
				->join('{{host}} h', 'h.hostId=l.hostId')
				->queryAll();
		if (count($rows)>0) {
			foreach($rows as $row) {
				$ssh = new ESsh($row['host'], $row['port'], $row['username'], $row['password']);
				if ($ssh==null) Tools::ajaxErrorReturn('无法连接发布主机');
				
				$archiveFile = $row['archivePath'].'/'.$row['archive'];
				$ssh->exec("/bin/rm -rf  $archiveFile");	//删除服务器上的
				@unlink(Yii::app()->params['archivesPath'].'/'.$row['archive']);	//删除本地的
				@unlink(Yii::app()->params['scriptPath'].'/'.$row['script']);	//删除本地脚本
				Yii::app()->db->createCommand()->delete('{{pub_log}}', 'logId=?', array($row['logId']));
			}
		}
		
		echo CJSON::encode(array());
		exit;
		
	}
	
	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		//用户可用项目列表
		$projects= Project::model()->findAll(array(
				'with'=>array('users'),
				'condition'=>'users.userId = ?',
				'params'=>array(Yii::app()->user->userId)
		));	//用户可用项目
		
		if (count($projects)<=0) {
			throw new CHttpException('403', '你暂时没有被分配项目');
		}
		
		$projectListData = CHtml::listData($projects,'projectId','projectName');
		
		$defaultProjectId = Yii::app()->user->defaultProject;
		if ($defaultProjectId==0) $defaultProjectId = $projects[0]->projectId;
		$currentProjectId = Yii::app()->request->getParam('id', '0');
		$currentProjectId = $currentProjectId=='0' ? $defaultProjectId : $currentProjectId;	//当前项目id
		$currentProject = Project::model()->findByPk($currentProjectId);
		
		if (is_null($currentProject)) {
			throw new CHttpException('500', '无此项目');
		}

		
		$model=new PubLog('search');
		$model->unsetAttributes();  // clear any default values
		
		if(isset($_GET['PubLog']))
			$model->attributes=$_GET['PubLog'];
		
		$this->render('index',array(
				'model'=>$model,  //upload model
				'projects'=>$projects,
				'currentProject'=>$currentProject
		));

	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=PubLog::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='log-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/publog/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'log-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'author'); ?>
		<?php echo $form->textField($model,'author',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'author'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'project_id'); ?>
		<?php echo $form->textField($model,'project_id'); ?>
		<?php echo $form->error($model,'project_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'archive'); ?>
		<?php echo $form->textField($model,'archive',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'archive'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'addtime'); ?>
		<?php echo $form->textField($model,'addtime'); ?>
		<?php echo $form->error($model,'addtime'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'host_id'); ?>
		<?php echo $form->textField($model,'host_id'); ?>
		<?php echo $form->error($model,'host_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/publog/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'log_id'); ?>
		<?php echo $form->textField($model,'log_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author'); ?>
		<?php echo $form->textField($model,'author',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'project_id'); ?>
		<?php echo $form->textField($model,'project_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'archive'); ?>
		<?php echo $form->textField($model,'archive',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'addtime'); ?>
		<?php echo $form->textField($model,'addtime'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'host_id'); ?>
		<?php echo $form->textField($model,'host_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/publog/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('log_id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->log_id), array('view', 'id'=>$data->log_id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author')); ?>:</b>
	<?php echo CHtml::encode($data->author); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('project_id')); ?>:</b>
	<?php echo CHtml::encode($data->project_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('archive')); ?>:</b>
	<?php echo CHtml::encode($data->archive); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('addtime')); ?>:</b>
	<?php echo CHtml::encode($data->addtime); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('host_id')); ?>:</b>
	<?php echo CHtml::encode($data->host_id); ?>
	<br />


</div>

protected/views/publog/admin.php
<?php
$this->breadcrumbs=array(
	'日志'=>array('index'),
	'管理',
);

$this->menu=array(
	array('label'=>'管理日志', 'url'=>array('admin')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('log-grid', {
		data: $(this).serialize()
	});
	return false;
});

");

Yii::app()->clientScript->registerScript('rollback', "
function rollback(t) {
	var url = $(t).attr('href');
	var log_id =  url.substring( url.lastIndexOf('=')+1 );
	
	jQuery('#logid').html(log_id);
	jQuery('#mydialog').dialog('open');
	return false;
}

");
?>
<script>
function pub() {

	var reason = jQuery.trim(jQuery('#reason').val());
	if (reason=='') {
		alert('请填写发布原因'); jQuery('#reason')[0].focus(); return false;
	}


	if (!confirm('请确认，要发布此日志id对应的档案')) return false;
	
	jQuery('#pub_button').attr('disabled', true);
	
	jQuery('.ui-dialog-titlebar').last().remove();
	jQuery('#publoading').dialog("open");
	
	jQuery.ajax({
		'type':'post',
		'url':'<?php echo $this->createUrl('pub/rollback');?>',
		'data':{
			'log_id':jQuery('#logid').html(),
			'reason':reason,
			'host_id':jQuery('#host').val(),
			'project_id':<?php echo $defaultProjectId;?>
		},
		'dataType':'json',
		'success':function(data, status) {
			if (data.error) {
				alert(data.error);
			}
			else {
				alert('发布成功');
				location.href="<?php echo $this->createUrl('log/admin');?>";
			}
			jQuery('#publoading').dialog("close");
			jQuery('#pub_button').attr('disabled', false);
		}
	});
	
	/*
	jQuery('.select-on-check').each(function(){
		
	});*/
	//alert(1);
}
</script>


<h1>管理日志</h1>
<p>选择项目:
	<?php

	echo CHtml::dropDownList('选择项目', $defaultProjectId, $projectListData, 
		array('onchange'=>'location.href="'. $this->createUrl('admin').'&project_id="+this.value;'));
	?>
</p>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'log-grid',
	'dataProvider'=>$model->search($defaultProjectId),
	//'filter'=>$model,
	'columns'=>array(
		'log_id',
	    array('header'=>'发布原因','name'=>'reason'),
		array('header'=>'发布者','name'=>'author'),
		array('header'=>'档案名','name'=>'archive'),
	        array('header'=>'已发布主机', 'type'=>'raw', 'name'=>'host'),
		array('header'=>'发布时间', 'value'=>'date("Y-m-d H:i:s", $data->addtime)'),
		array(
		    'header'=>'操作',
			'class'=>'CButtonColumn',
		     //   'template'=>'{view} {delete} {pub}',
				'template'=>'{view} {delete}',
		        'htmlOptions'=>array('style'=>'width:150px'),
		        'buttons'=>array(
			   /* 
			   	edit by yanxiaowei@20110624: cancel the function :rollback
			    'pub'=>array(
				'label'=>'回滚',
				'click'=>'js:function(){ return rollback(this);}',
				'url'=>'Yii::app()->createUrl("pub/rollback", array("log_id"=>$data->log_id) )',
			    )
				*/
			)
		),
	),
)); ?>


<?php
 $this->beginWidget('zii.widgets.jui.CJuiDialog', array(
      'id'=>'mydialog',
      // additional javascript options for the dialog plugin
      'options'=>array(
          'title'=>"回滚",
	  'resizable'=>false,
          'autoOpen'=>false,
	  'disabled'=>true,
	  'modal'=> true,
	  'closeOnEscape'=>false,
	  'draggable'=>false,
	  'width'=>500,
	  'height'=>300,
      ),
  ));?>
	<div class="row">
		<?php echo CHtml::label('日志id','log_id');?>
		<?php echo CHtml::tag("span", array('id'=>'logid'));?>
	</div>

	<div class="row">
		<?php echo CHtml::label('回滚原因','reason'); ?>
		<?php echo CHtml::textField('reason', '', array('id'=>'reason', 'size'=>30,'maxlength'=>100)); ?>
	</div>
	
	<div class="row buttons">
		<?php 
		echo CHtml::button('回滚到此版本', array('id'=>'pub_button', 'onclick'=>'pub()'));
		?>
	</div>

<?php

 $this->endWidget('zii.widgets.jui.CJuiDialog');
 ?>


<?php
 $this->beginWidget('zii.widgets.jui.CJuiDialog', array(
      'id'=>'publoading',
      // additional javascript options for the dialog plugin
      'options'=>array(
          'title'=>false,
	  'resizable'=>false,
          'autoOpen'=>false,
	  'disabled'=>true,
	  'modal'=> true,
	  'closeOnEscape'=>false,
	  'draggable'=>false,
	  'height'=>60,
      ),
  ));

      echo '发布中...请稍候...';

 $this->endWidget('zii.widgets.jui.CJuiDialog');
 ?>

protected/views/publog/create.php
<?php
$this->breadcrumbs=array(
	'Logs'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Log', 'url'=>array('index')),
	array('label'=>'Manage Log', 'url'=>array('admin')),
);
?>

<h1>Create Log</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/publog/update.php
<?php
$this->breadcrumbs=array(
	'Logs'=>array('index'),
	$model->log_id=>array('view','id'=>$model->log_id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Log', 'url'=>array('index')),
	array('label'=>'Create Log', 'url'=>array('create')),
	array('label'=>'View Log', 'url'=>array('view', 'id'=>$model->log_id)),
	array('label'=>'Manage Log', 'url'=>array('admin')),
);
?>

<h1>Update Log <?php echo $model->log_id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/publog/view.php
<?php
$this->pageTitle=Yii::app()->name . ' - 查看发布日志';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>查看发布日志 <?php echo $model->project->projectName?>:<?php echo CHtml::encode($model->reason); ?></h1>
			</div>
		</div>
		<div class="MetadataView">
      <div class="view-toolbar">
          <?php echo CHtml::link('返回', array('/publog/index'));?>
          <?php echo CHtml::link('回滚', array('/publog/rollback'));?>
        </div>
        <table>
          <colgroup>
          <col style="width:20%">
          <col style="width:30%">
          <col style="width:20%">
          <col style="width:30%">
          </colgroup>
          <tbody>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'pubUser'); ?></th>
              <td colspan="1">
              <?php echo CHtml::value($model, 'pubUser'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'reason'); ?></th>
              <td colspan="1">
              <?php echo CHtml::value($model, 'reason'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'host'); ?></th>
              <td colspan="1">
              <?php echo CHtml::value($model, 'host'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'createTime'); ?></th>
              <td colspan="1">
              <?php echo CHtml::value($model, 'createTime'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'fileList'); ?></th>
              <td colspan="3">
              <?php
              echo nl2br($model->fileList); 
              ?>
              </td>
            </tr>
          </tbody>
        </table>
		
		</div>
	</div>

</div>