protected/models/User.php
<?php

class User extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, email', 'required', 'on'=>'insert'),
			array('password', 'safe', 'on'=>'update'),
			array('email', 'email'),
			array('role', 'safe'),
			array('username', 'length', 'max'=>50),
			array('password', 'length', 'max'=>100),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('userId, username, password, email, role', 'safe', 'on'=>'search'),
		);
	}

	
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		    'projects'=>array(self::MANY_MANY, 'Project', '{{project_user}}(userId, projectId)'),
		    'hosts'=>array(self::MANY_MANY, 'Host', '{{user_host}}(userId, hostId)'),
		);
	}

	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'userId' => 'User',
			'defaultProject' => '默认项目',
			'username' => '用户名',
			'password' => '密码',
			'email' => '邮箱',
			'role' => '角色'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('userId',$this->userId);
		$criteria->compare('defaultProject',$this->defaultProject,true);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('role',$this->role,true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}

protected/controllers/HostController.php
<?php

class HostController extends Controller
{

	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}
	
	
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to perform 'index' and 'view' actions
						'roles'=>array('admin'),
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*')
				)
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Host;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$distributeHostList = Yii::app()->request->getPost('distributeHostList', '');
		if(isset($_POST['Host']))
		{
			$model->attributes=$_POST['Host'];
			if($model->save()) {
				$model->insertDistributeHost($distributeHostList);
				$this->redirect(array('view','id'=>$model->hostId));
			}
			
		}

		$this->render('create',array(
			'model'=>$model,
			'distributeHostList'=>$distributeHostList
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		$distributeHostList = '';
		$lists = Yii::app()->db->createCommand()
						->from('{{distribute_host}}')
						->select('host, port, pubPath, archivePath, tmpPath, scriptLogPath')
						->where('hostId=?')
						->queryAll(false, array($model->hostId));
		if (count($lists)>0) {
			foreach($lists as $key => $value) {
				$lists[$key] = join(':', $value);
			}
			$distributeHostList = join("\n", $lists);
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Host']))
		{
			$model->attributes=$_POST['Host'];
			if($model->save())
				$distributeHostList = Yii::app()->request->getPost('distributeHostList', '');
				$model->deleteDistributeHost();
				$model->insertDistributeHost($distributeHostList);
				$this->redirect(array('view','id'=>$model->hostId));
		}

		$this->render('update',array(
			'model'=>$model,
			'distributeHostList'=>$distributeHostList
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			$sql = "DELETE FROM {{project_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));

			$sql = "DELETE FROM {{user_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			$sql = "DELETE FROM {{distribute_host}} WHERE hostId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new Host('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Host']))
			$model->attributes=$_GET['Host'];

		$this->render('index',array(
			'model'=>$model,
		));
	}



	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Host::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='host-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	

}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{

	public function filters()
	{
		return array(
				'accessControl', // perform access control for CRUD operations
		);
	}

	
	public function accessRules()
	{
		return array(
				array('allow',  // allow all users to perform 'index' and 'view' actions
						'actions'=>array('index', 'view', 'create'),
						'roles'=>array('admin'),
						'users'=>array('@'),
				),
				array('allow',
						'actions'=>array('update', 'delete'),
						'users'=>array('admin'),
						'roles'=>array('admin')
				),
				array('deny',  // deny all users
						'users'=>array('*')
				)
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		$projectListData = CHtml::listData(Project::model()->findAll(),'projectId','projectName');
		$hostListData = CHtml::listData(Host::model()->findAll(),'hostId','hostText', 'hostType');
		$prodHostListData = isset($hostListData[1]) ? $hostListData[1] : array(); //生产主机
		$testHostListData = isset($hostListData[0]) ? $hostListData[0] : array(); //测试主机
		
		$userProjectIds = array();	//用户项目ID列表
		$userTestHostIds = array();
		$userProdHostIds = array();

		if(isset($_POST['User']))
		{
			
			$model->attributes=$_POST['User'];

			if($model->validate()) {
				$model->password = md5($model->password);
				$model->save(false);
				$userProjectIds = isset($_POST['userProjectIds'])?$_POST['userProjectIds']: array();
				if (is_array($userProjectIds) && count($userProjectIds)>0) {
					$sql = "INSERT INTO {{project_user}} (projectId, userId) VALUES ";
					foreach($userProjectIds as $userProjectId) {
						 $sql .= " ($userProjectId, $model->userId),";
					}
					$sql = rtrim($sql, ",");
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				//主机列表
				$userProdHostIds = isset($_POST['userProdHostIds']) ? $_POST['userProdHostIds'] : array();
				$userTestHostIds = isset($_POST['userTestHostIds']) ? $_POST['userTestHostIds'] : array();
				$userHostIds = array_merge($userProdHostIds, $userTestHostIds);
				if (is_array($userHostIds) && count($userHostIds)>0) {
					$sql = "INSERT INTO {{user_host}} (userId, hostId) VALUES ";
					foreach($userHostIds as $userHostId) {
						$sql .= " ($model->userId, $userHostId),";
					}
					$sql = trim($sql, ",");
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				$this->redirect(array('view','id'=>$model->userId));
			}
		}

		$this->render('create',array(
			'model'=>$model,
			'projectListData'=>$projectListData,
			'prodHostListData'=>$prodHostListData,
		    'testHostListData'=>$testHostListData,
			'userProjectIds'=>$userProjectIds,
		    'userTestHostIds'=>$userTestHostIds,
		    'userProdHostIds'=>$userProdHostIds
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		
		//用户项目ID列表
		$userProjectIds = Yii::app()->db->createCommand()
								->from('{{project_user}}')
								->select('projectId')
								->where('userId=?')
								->queryColumn(array($id));
		if (is_null($userProjectIds)) $userProjectIds = array();	
		
		//用户测试主机ID列表
		$userTestHostIds = Yii::app()->db->createCommand()
								->from('{{user_host}} t')
								->select('t.hostId')
								->join('{{host}} h', 't.hostId=h.hostId AND hostType=0')
								->where('userId=?')
								->queryColumn(array($id));
		if (is_null($userTestHostIds)) $userTestHostIds = array();
		
		//用户产生主机ID列表
		$userProdHostIds = Yii::app()->db->createCommand()
								->from('{{user_host}} t')
								->select('t.hostId')
								->join('{{host}} h', 't.hostId=h.hostId AND hostType=1')
								->where('userId=?')
								->queryColumn(array($id));
		if (is_null($userProdHostIds)) $userProdHostIds = array();
		
		
		$projectListData = CHtml::listData(Project::model()->findAll(),'projectId','projectName');
		$hostListData = CHtml::listData(Host::model()->findAll(),'hostId','hostText', 'hostType');
		$prodHostListData = isset($hostListData[1]) ? $hostListData[1] : array(); //生产主机
		$testHostListData = isset($hostListData[0]) ? $hostListData[0] : array(); //测试主机

		if(isset($_POST['User']))
		{
			$oldPassword = $model->password;
			$model->attributes=$_POST['User'];
			
			if ($model->validate()) {
				if ($model->password=='' || $oldPassword==$model->password) $model->password=$oldPassword;
				else $model->password=md5($model->password);
				$model->save(false);
				$userProjectIds = isset($_POST['userProjectIds'])?$_POST['userProjectIds']: array();

				//$model->save()
				//项目列表
				$sql = "DELETE FROM {{project_user}} WHERE userId=?";
				Yii::app()->db->createCommand($sql)->execute(array($model->userId));
				if (is_array($userProjectIds) && count($userProjectIds)>0) {
					$sql = "INSERT INTO {{project_user}} (projectId, userId) VALUES ";
					foreach($userProjectIds as $userProjectId) {
						 $sql .= " ($userProjectId, $model->userId),";
					}
					$sql = rtrim($sql, ",");
					
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				//主机列表
				$userProdHostIds = isset($_POST['userProdHostIds']) ? $_POST['userProdHostIds'] : array();
				$userTestHostIds = isset($_POST['userTestHostIds']) ? $_POST['userTestHostIds'] : array();
				$userHostIds = array_merge($userProdHostIds, $userTestHostIds);
				$sql = "DELETE FROM {{user_host}} WHERE userId=?";
				Yii::app()->db->createCommand($sql)->execute(array($model->userId));
				if (is_array($userHostIds) && count($userHostIds)>0) {
					$sql = "INSERT INTO {{user_host}} (userId, hostId) VALUES ";
					foreach($userHostIds as $userHostId) {
						$sql .= " ($model->userId, $userHostId),";
					}
					$sql = trim($sql, ",");
					Yii::app()->db->createCommand($sql)->execute();
				}
				
				$this->redirect(array('view','id'=>$model->userId));
			}
		}

		$model->password='';
		$this->render('update',array(
			'model'=>$model,
			'projectListData'=>$projectListData,
			'prodHostListData'=>$prodHostListData,
		    'testHostListData'=>$testHostListData,
			'userProjectIds'=>$userProjectIds,
		    'userTestHostIds'=>$userTestHostIds,
		    'userProdHostIds'=>$userProdHostIds
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			$model = $this->loadModel($id);
			if ($model->username==Yii::app()->user->name) 
				throw new CHttpException('403', '不能删除自己');
			if ($model->username=='admin')
				throw new CHttpException('403', 'Admin用户不能删除');
			// we only allow deletion via POST request
			$model->delete();
			
			$sql = "DELETE FROM {{project_user}} WHERE userId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			$sql = "DELETE FROM {{user_host}} WHERE userId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));
			
			$sql = "DELETE FROM {{user_tag}} WHERE userId=?";
			Yii::app()->db->createCommand($sql)->execute(array($id));

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('index',array(
			'model'=>$model,
		));
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
    <div class="wide form">
        <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'user-form',
                'enableAjaxValidation'=>false,
        )); ?>
      <div class="view-toolbar">
          <?php echo CHtml::link('取消', array('/user/index'));?>&nbsp;|&nbsp;
          <?php echo CHtml::submitButton($model->isNewRecord ? '添加' : '保存'); ?>
        </div>
        <table>
          <colgroup>
          <col style="width:20%">
          <col style="width:30%">
          <col style="width:20%">
          <col style="width:30%">
          </colgroup>
          <tbody>
            <tr>
              <th><?php echo $form->labelEx($model,'username'); ?></th>
              <td colspan="1">
              <?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>50)); ?>
              <?php echo $form->error($model,'username'); ?>
              </td>
              <th><?php echo $form->labelEx($model,'password'); ?></th>
              <td colspan="1">
              <?php echo $form->passwordField($model,'password',array('size'=>60,'maxlength'=>50)); ?>
              <?php echo $model->isNewRecord ? '' : '<br />留空将不修改密码';?>
              <?php echo $form->error($model,'$password'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo $form->labelEx($model,'email'); ?></th>
              <td colspan="1">
				<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?>
				<?php echo $form->error($model,'email'); ?>
              </td>
              <th><?php echo CHtml::label('可用项目','userProjectIds[]'); ?></th>
              <td colspan="1">
              		<?php echo CHtml::dropDownList('userProjectIds[]',
						$userProjectIds,
						$projectListData,
						array(
							'multiple'=>true,
						        'style'=>'width:520px;height:100px;'	
						)
					);?>
			</td>
            </tr>
            <?php if (Yii::app()->user->username=='admin') :?>
            <tr>
              <th><?php echo $form->labelEx($model,'role'); ?></th>
              <td colspan="1">
				<?php echo $form->dropDownList($model,'role',array('admin'=>'管理员', 'user'=>'用户')); ?>
				<?php echo $form->error($model,'role'); ?>
              </td>
              <th>--</th>
              <td colspan="1">
              	--
			</td>
            </tr>
           <?php endif; ?>
            <tr>
              <th><?php echo CHtml::label('可用测试服务器','userTestHostIds[]');?></th>
              <td colspan="1">
				<?php echo CHtml::dropDownList('userTestHostIds[]',
						$userTestHostIds,
						$testHostListData,
						array(
							'multiple'=>true,
						        'style'=>'width:520px;height:100px;'	
						)
					);?>
              </td>
              <th><?php echo CHtml::label('可用生成服务器','userProdHostIds[]');?></th>
              <td colspan="1">
              		<?php echo CHtml::dropDownList('userProdHostIds[]',
						$userProdHostIds,
						$prodHostListData,
						array(
							'multiple'=>true,
						        'style'=>'width:520px;height:100px;'	
						)
					);?>
			 </td>
            </tr>
          </tbody>
        </table>
    </div>
    <?php $this->endWidget(); ?>
  </div>

protected/views/user/create.php
<?php
$this->pageTitle=Yii::app()->name . ' - 添加用户';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>添加用户</h1>
			</div>
		</div>
		<div class="MetadataView">

		<?php echo $this->renderPartial('_form', 
			array(
				'model'=>$model,
				'projectListData'=>$projectListData,
				'prodHostListData'=>$prodHostListData,
			    'testHostListData'=>$testHostListData,
				'userProjectIds'=>$userProjectIds,
			    'userTestHostIds'=>$userTestHostIds,
			    'userProdHostIds'=>$userProdHostIds
			)); ?>
		
		</div>
	</div>

</div>

protected/views/user/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - 用户列表';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>用户列表</h1>
			</div>
		</div>
		<div class="MetadataView">
		
		<?php $this->widget('zii.widgets.grid.CGridView', array(
			'id'=>'user-grid',
			'htmlOptions'=>array(
					'class'=>'cgrid-view'
			),
			'dataProvider'=>$model->search(),
			'filter'=>$model,
			'columns'=>array(
				array('header'=>'用户名', 'name'=>'username'),
				array('header'=>'邮箱', 'name'=>'email'),
				array(
					'header'=>'操作',
					'class'=>'CButtonColumn',
				),
			),
		)); ?>
		
		</div>
	</div>

</div>

protected/views/user/update.php
<?php
$this->pageTitle=Yii::app()->name . ' - 更新用户';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>更新用户 <?php echo $model->username; ?></h1>
			</div>
		</div>
		<div class="MetadataView">

<?php echo $this->renderPartial('_form', 
	array(
			'model'=>$model,
			'projectListData'=>$projectListData,
			'prodHostListData'=>$prodHostListData,
		    'testHostListData'=>$testHostListData,
			'userProjectIds'=>$userProjectIds,
		    'userTestHostIds'=>$userTestHostIds,
		    'userProdHostIds'=>$userProdHostIds
	    )); ?>

		
		</div>
	</div>

</div>

protected/views/user/view.php
<?php
$this->pageTitle=Yii::app()->name . ' - 查看用户';
?>
<div>
	<div class="GridView" style="overflow: auto;">
		<div>
			<div style="" class="TitleBarView">
				<h1>查看用户 <?php echo $model->username; ?></h1>
			</div>
		</div>
		<div class="MetadataView">
      <div class="view-toolbar">
          <?php echo CHtml::link('返回', array('/user/index'));?>
        </div>
        <table>
          <colgroup>
          <col style="width:20%">
          <col style="width:30%">
          <col style="width:20%">
          <col style="width:30%">
          </colgroup>
          <tbody>
            <tr>
              <th><?php echo CHtml::activeLabel($model,'username'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'username'); ?>
              </td>
              <th><?php echo CHtml::activeLabel($model,'email'); ?></th>
              <td colspan="1">
              <?php echo CHTML::value($model, 'email'); ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::label('可用项目','userProjectIds');?></th>
              <td colspan="3">
              <?php 
              	if (isset($model->projects) && is_array($model->projects)) :
              		$no = 1;
              		foreach ($model->projects as $project) :
              			echo CHtml::link($no.':'.$project->projectName, array('project/view', 'id'=>$project->projectId));
              			echo '&nbsp;';
              			$no++;
              		endforeach;
              	endif;
              ?>
              </td>
            </tr>
            <?php 
            //可用测试服务器
            $userTestHosts = array();
            //可用生成服务器
            $userProdHosts = array();
            if (isset($model->hosts) && is_array($model->hosts)) {
            	foreach($model->hosts as $host) {
            		if ($host->hostType==1) {
            			$userProdHosts[$host->hostId] = $host->hostText;
            		}
            		else {
            			$userTestHosts[$host->hostId] = $host->hostText;
            		}
            	}
            
            }
            ?>
            <tr>
              <th><?php echo CHtml::label('可用测试服务器','userTestHostIds');?></th>
              <td colspan="3">
              <?php 
              	if (is_array($userTestHosts)) :
              		$no = 1;
              		foreach ($userTestHosts as $key => $value) :
              			echo CHtml::link($no.':'.$value, array('host/view', 'id'=>$key));
              			echo '&nbsp;';
              			$no++;
              		endforeach;
              	endif;
              ?>
              </td>
            </tr>
            <tr>
              <th><?php echo CHtml::label('可用生成服务器','userProdHostIds');?></th>
              <td colspan="3">
              <?php 
              	if (is_array($userProdHosts)) :
              		$no = 1;
              		foreach ($userProdHosts as $key => $value) :
              			echo CHtml::link($no.':'.$value, array('host/view', 'id'=>$key));
              			echo '&nbsp;';
              			$no++;
              		endforeach;
              	endif;
              ?>
              </td>
            </tr>
          </tbody>
        </table>
		
		</div>
	</div>

</div>